### ISSUE TITLE
taxonomy plotting utility

### ISSUE THREAD

**Issue by coder47040** [nightrome/cocostuff#10]
Hello COCO Stuff authors,

The coco stuff taxonomy here is very cool: https://raw.githubusercontent.com/nightrome/cocostuff10k/master/dataset/cocostuff-labelhierarchy.png

Could you please share the tools/code you used to plot the taxonomy? Thank you.

**Comment by nightrome** [comment]
Hi, use the code of the old 10k dataset:
https://github.com/nightrome/cocostuff10k/blob/master/dataset/code/CocoStuffClasses.m#L465
