### ISSUE TITLE
Undefined label index in COCO stuff

### ISSUE THREAD

**Issue by johnwlambert** [nightrome/cocostuff#11]
Hi Caesar,

Question for you -- I'm looking at the COCO stuff annotation for `000000351710.png`:

![image](https://user-images.githubusercontent.com/16724970/62812849-6b665f80-babc-11e9-8f75-acf3c6016117.png)

I see [in the label definitions](https://github.com/nightrome/cocostuff/blob/master/labels.md) that 0 represents unlabeled, but I can't find a definition for 255. What does the 255 intensity value represent?

```
Array([[180, 180, 180, 180,  95, 156, 156, 156, 156, 156, 156, 156, 156],
       [ 95,  95, 180,  95,  95,  95, 156, 156, 156, 156, 156, 156, 156],
       [180, 180, 180, 180,  95,  95,  95,  95, 156, 156, 156, 156, 156],
       [ 95,  95,  95,  95,  95,  95,  95,  95, 168, 168, 168, 150, 150],
       [ 95,   0,  95,  95,  95,  95,  95,  95, 168, 168,  95,  95,  95],
       [ 96,   0,   3,   2, 139, 139, 139, 148, 148,   3, 148, 148, 148],
       [141, 141,   3,   3, 255, 255, 255, 255, 148, 255, 255, 255, 148],
       [148, 148, 148, 148, 255, 255, 255, 255, 255, 255, 255, 255, 148],
       [148, 148, 148, 148, 255, 255, 255, 255, 255, 255, 255, 255, 141],
       [148, 148, 148, 148, 148, 255, 255, 148, 148, 255, 255, 141, 141]],
      dtype=uint8)
```
(cc'ing @liuzhuang13)

**Comment by nightrome** [comment]
Hi @johnwlambert. Good to meet you on this repo, too :-D. https://github.com/nightrome/cocostuff says that 255 stands for unlabeled. I am not sure why this is the case here, but I believe that these pixels have the "crowd"-label in COCO. That label is used when there are more than 5 instances in a region and it isn't feasible to delineate the individual instances. Unfortunately a few "adversarial" annotators in COCO have drawn some funny crowd annotations, see: https://github.com/cocodataset/cocoapi/issues/40
