### ISSUE TITLE
COCO stuff 2017 version for downloading

### ISSUE THREAD

**Issue by superkoma** [nightrome/cocostuff#12]
Hi, could you please share me the link of coco-stuff 2017 version annotations for COCO 2017 Stuff Segmentation Task? Actually it's the version of (train 40K, val 5K, test-dev 5K, test-challenge 5K). I've searched the internet for that but I only found the version of (train 118K, val 5K, test-dev 20K, test-challenge 20K).
Thanks.

**Comment by nightrome** [comment]
Hi. Unfortunately that version is no longer available. However the latest version includes those images: http://cocodataset.org/#download

**Comment by superkoma** [comment]
> Hi. Unfortunately that version is no longer available. However the latest version includes those images: http://cocodataset.org/#download

Thanks for your kind reply. I've downloaded these images, but the annotations used in that paper I want to reproduce are for (train 40K, val 5K, test-dev 5K, test-challenge 5K). Quite a pity to hear about that.

**Comment by nightrome** [comment]
@superkoma I think I found a backup of the train/val splits. Please check the files at: https://drive.google.com/open?id=1gPTllGIS_uVE1w30EKETs9W_O6HRcMLO

**Comment by superkoma** [comment]
@nightrome Many thanks and wish you all the best.
