### ISSUE TITLE
Question about confusion matrix indices

### ISSUE THREAD

**Issue by zacurr** [nightrome/cocostuff#13]
I trained semantic segmentation model using "stuffthingmaps_trainval2017.zip"
(Stuff+thing PNG-style annotations on COCO 2017 trainval	)

In this case, 
thing+stuff labels cover indices 0-181 and 255 indicates the 'unlabeled' or void class.

I think the below line 
https://github.com/nightrome/cocostuff/blob/master/models/deeplab/evaluate_performance.py#L98
confusion[g - 1, d - 1] += c
(this is for json format annotation,
COCO-style annotations  (json file) cover indices 1-182)

should be changed to 
confusion[g, d] += c

since g and d can be 0.

This modification does not change the performance on leaf category.

However, If I add metric for superclass to evaluation_performance.py based on coccostuffapi, 
This modification gives me very different values for superclass category performance. 
(much higher)

Do I miss something?

**Comment by nightrome** [comment]
Hi. I think you are right. Please check if this resolves the problem: https://github.com/nightrome/cocostuff/commit/0b9b7acfaab1d08ec4ce97ca3a5f90513c8d3d3b
The bug was not noticeable as it basically just changed the ordering of the classes.

**Comment by zacurr** [comment]
Thank you. It resolves the problem. 

When I print per-class mIoU results with original indexing (g-1,d-1)
11 classes give NaN (fire hydrant, giraffe, umbrella, shoe, bottle, bed, dining table, window, toilet, refrigerator, toothbrush)
and super class results (only stuff super class)
Super Category Performance on coco-stuff val: 59.55% (macc), 72.06% (pacc), 45.50% (miou), 56.61% (fwiou)
(ceiling: 0, sky: 0.277,...)

and When I do it with (g,d) indexing
11 classes that give NaN : street sign, hat, shoe, eye glasses, plate, mirror, window, desk, door, blender, hair brush
This corresponds to https://github.com/nightrome/cocostuff/blob/master/labels.md

and Super class results..
Super Category Performance on coco-stuff val: 75.01% (macc), 81.79% (pacc), 61.62% (miou), 70.17% (fwiou)
(ceiling: 0.608, sky: 0.863,...)

Even though it is not directly comparable, this is close to COCO Stuff superclass results.
http://cocodataset.org/#stuff-leaderboard

**Comment by nightrome** [comment]
Thanks for the feedback!
