### ISSUE TITLE
How can I produce colored maps during testing?

### ISSUE THREAD

**Issue by Ha0Tang** [nightrome/cocostuff#14]

**Comment by nightrome** [comment]
Please elaborate on what you mean.

**Comment by Ha0Tang** [comment]
![image](https://user-images.githubusercontent.com/23024709/70294436-5afc9200-17db-11ea-8fd2-1684550fb951.png)

I would like to produce colored maps similar to this figure.

**Comment by nightrome** [comment]
Take a look at this: https://github.com/nightrome/cocostuff10k/blob/master/dataset/code/demo_cocoStuff.m
