### ISSUE TITLE
How to make cocostuff dataset with coco json file?

### ISSUE THREAD

**Issue by Paddy-Xu** [nightrome/cocostuff#15]
Hi,

I am trying to train a hybrid task cascade net (HTC) and the mask branch requires the format of cocostuff dataset. I am wondering if it is possible to convert from coco json file to a cocostuff dataset ?

**Comment by nightrome** [comment]
You can download the annotations in COCO format from https://cocodataset.org/#download.

**Comment by Paddy-Xu** [comment]
Hi, thanks, but I rather mean to create custom dataset in coco-stuff format. Like there are lots of tutorials on how to make own dataset in coco format, but I haven't found any that is able to make coco-stuff format

**Comment by nightrome** [comment]
In the old COCO-Stuff 10k dataset we have a bunch of tools that you may want to take a look at: https://github.com/nightrome/cocostuff10k/tree/master/dataset/code/conversion
