### ISSUE TITLE
Stuff dataset .

### ISSUE THREAD

**Issue by Zhangwenyao1** [nightrome/cocostuff#16]
I only want a stuff data set, How can I separate the outdoor of stuff part from this data set? Are there have a data set only includes outdoor classes in stuff? Thank you!

**Comment by nightrome** [comment]
You can download the stuff dataset here or at https://cocodataset.org/#download. I don't think COCO has any metadata regarding indoor/outdoor, but maybe the presence of certain classes (e.g. car, boat, sky) can help.

**Comment by Zhangwenyao1** [comment]
Thank you!  But What I want are the sky, solid, ground, water in  the stuff, things such car, boat  as are not helpful for me. So I want a part about the terrain and outdoor surrounding.
![image](https://user-images.githubusercontent.com/56442860/104806044-7a078900-580f-11eb-8517-890189616aee.png)
