### ISSUE TITLE
test sets available?

### ISSUE THREAD

**Issue by dmadras** [nightrome/cocostuff#18]
This might be a stupid question - in the Versions of COCO-Stuff section, it says "it includes all 164K images from COCO 2017 (train 118K, val 5K, test-dev 20K, test-challenge 20K)." However, I only see the train and val sets available for download in the Downloads section. Are either of the test sets available?

**Comment by jrruijli** [comment]
COCO does not release annotations for any of their test sets. You can get
the test images from the official website: https://cocodataset.org/#download

Evaluation goes through their server.

Cheers,
Jasper

**Comment by dmadras** [comment]
Okay thank you! I suppose the readme is a little confusing in that respect - I appreciate the clarification.
