### ISSUE TITLE
What is the range of the labels?

### ISSUE THREAD

**Issue by CoinCheung** [nightrome/cocostuff#19]
Hi,

Since there are 11 classes are remove, does it mean that the labels are range from 0-170 plusing 255 ? Or does is mean that the labels are still range from 0-191, and we need to map them to 0-170 manually?

**Comment by nightrome** [comment]
Hi. Please see [this section](https://github.com/nightrome/cocostuff#label-names--indices) in the readme. The 11 classes are removed from COCO and among the first 91. So yes, if your training framework requires you to have consecutive labels, you'll need to rearrange them.
