### ISSUE TITLE
deploy.prototxt unavailable

### ISSUE THREAD

**Issue by shridharkini6** [nightrome/cocostuff#2]
Hi
could you supply with deploy.prototxt files to test.
Thanks

**Comment by nightrome** [comment]
It's called test.prototxt: https://github.com/nightrome/cocostuff/tree/master/models/deeplab/cocostuff/config/deeplabv2_vgg16

**Comment by edoaxyz** [comment]
A deploy.prototxt file doesn't contain arguments like ${FEATURE_DIR} or ${EXP}.

**Comment by nightrome** [comment]
Note that these placeholders are used in the Deeplab repository. They have another script that replaces them with actual values and writes the final prototxt files to disk.

**Comment by edoaxyz** [comment]
Can you share the link to this script?

**Comment by nightrome** [comment]
My modified copy of that script is at https://github.com/nightrome/cocostuff/blob/master/models/deeplab/run_cocostuff_resnet101.sh#L55
