### ISSUE TITLE
Do annotations have the instance-wise bounding boxes?

### ISSUE THREAD

**Issue by quangvnai** [nightrome/cocostuff#20]
Thank you, authors, for the great work. As I've examined the annotations, it seems like the bounding boxes are provided per category rather than per instance. For example, there are 2 windows in the image but only a single box covering 2 windows. Am I correct?
If so, do you have the instance-wise annotation?
Many thanks beforehand!

**Comment by nightrome** [comment]
Hi. We don't provide bounding boxes or instance annotations. These are from the original COCO dataset. Please see https://cocodataset.org. I believe window may be one of the few classes that were removed from the final dataset: https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/

**Comment by quangvnai** [comment]
Thanks for your quick reply.
`window` class is just one of my example.
In fact, I downloaded `stuff_trainval2017.zip` from your `README.md`. When uncompressing, I got 2 files: `stuff_val2017.json` and `stuff_train2017.json`. 
![image](https://user-images.githubusercontent.com/30741785/135247624-6e947eb4-68f8-4d42-a363-a93a4f0cb01a.png)

* The `stuff_val2017.json` has the following structure (similar to `instance_val2017.json` of COCO):
![image](https://user-images.githubusercontent.com/30741785/135247899-f95b0f66-7f20-4820-b2af-1d734ec2293f.png)

* Then I plot the `bbox` in this annotation file, I got the visualization as follows.
![image](https://user-images.githubusercontent.com/30741785/135247558-af9d7c4f-a1d8-44ff-99da-b773b966ffaa.png)

## So, my question, again, is:
* Such `bbox` are generated from the segmentation annotations? We obviously see that the `bbox` for the `light` covers all the `light` in the image.

**Comment by nightrome** [comment]
Okay, if you are referring to the stuff labels `window-blind` and `window-other` [here](https://github.com/nightrome/cocostuff/blob/master/labels.txt), these are annotated on a superpixel level and don't have instance information. The boxes are simply around connected regions and should probably not be used for object detection or instance segmentation purposes.
