### ISSUE TITLE
Which stuff classes are included in the coco stuff challenge

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [nightrome/cocostuff#21]
Hello,

Sorry if this has been answered but I am having a bit of difficulty trying to figure out which stuff classes (as specifically as possible) were included in the Coco 2017 Stuff challenge. I'm imagining the original 80 thing classes (from the 91 with some removed) are included, but which of the remaining 171 classes were included in the Stuff challenge?

Thanks

**Comment by nightrome** [comment]
Hi. Take a look at the description at https://github.com/nightrome/cocostuff#versions-of-coco-stuff
