### ISSUE TITLE
Annotation link broken

### ISSUE THREAD

**Issue by TimDarcet** [nightrome/cocostuff#22]
Hi,
The annotation link (http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip) seems broken. Do you know how I could download the annotations ? Thank you for your help

**Comment by jrruijli** [comment]
Hi,

I just tried it and it worked for me. Can you try again? Please note that
you could also encounter some safety feature of your browser.

Cheers,
Jasper

**Comment by TimDarcet** [comment]
Hi,
Thank you for your quick answer. I've finally managed to download it, it seems it was blocked by my organisation's network. Downloading it from an outside machine worked.
Thank you again,
Tim
