### ISSUE TITLE
Checking labels from the png maps

### ISSUE THREAD

**Issue by buncybunny** [nightrome/cocostuff#23]
@nightrome Hello there! 

I'm trying to check the class-number-wise labeled map but couldn't find anything like that. 
The image below is the example of PASCAL VOC.
<img src="https://blog.kakaocdn.net/dn/5hrNl/btqRgi23cdn/TjMYD0D6LRESM7WDPRkxd0/img.png" width="70%">
<img src="https://blog.kakaocdn.net/dn/T9kKd/btqQ7TKkzdr/rKX4RqtNSkKzUSG6IS8Xn1/img.png" width="70%">
Doesn't cocostuff have these kind of labeled maps? 
I opened the images of stuffthingmaps_trainval2017 with numpy, and it seems like they only have the value of (0,255) - which only represents the brightness.

**Comment by nightrome** [comment]
Hi. Here is a random image `000000000049.png` from `stuffthingmaps_trainval2017`:
![000000000049](https://user-images.githubusercontent.com/1212780/144369679-5870a990-3542-4c11-ae7d-b925137ce442.png)

You can see that the greyscale values correspond to the class labels, not brightness. 
The label map can be seen at: https://github.com/nightrome/cocostuff/blob/master/labels.txt
Note that to be compatible with the VOC format we set 255 to void/unlabeled.
