### ISSUE TITLE
About the stuff categories annotation.

### ISSUE THREAD

**Issue by JimmyMa99** [nightrome/cocostuff#25]
panoptic_semseg_train2017/000000000247.png
![000000000247](https://user-images.githubusercontent.com/101508488/164885924-19228ef2-0296-43b7-9153-455b25f139bb.png)

I want to know why the greyscale of the sky is 119, but as you have mentioned in [this issue](https://github.com/nightrome/cocostuff/issues/23), the sky-other in the [labels](https://github.com/nightrome/cocostuff/blob/master/labels.md) may 157 or 146(157-11)(some classes have been removed)?

I am so confused that how to build the mapping relationships between classes and greyscale in the .png

**Comment by nightrome** [comment]
Are you sure it's systematic and not a single wrong annotation? Note that panoptic_semseg_train2017 is not from this repo. Maybe you can ask the authors of the panoptic segmentation annotations?

**Comment by JimmyMa99** [comment]
Thank you for your reply.
I'll ask the author of the panoptic segmentation annotations
