### ISSUE TITLE
Noun Annotations

### ISSUE THREAD

**Issue by Delphboy** [nightrome/cocostuff#26]
Hi, 

My supervisors and I are currently working on a paper analysing the COCO data set. As part of this we need to identify nouns within the COCO captions as “things” or “stuff”. In Section 4.1 of your COCO-Stuff paper, you mention that you underwent a similar process tagging the nouns by hand. I was wondering if you would please be able to share this data with us to save us having to undertake a similar venture. We would of course credit your work through appropriate citations.

Many thanks

**Comment by nightrome** [comment]
Hi. Unfortunately I don't have that code/data anymore. However, it should only take a day or two to reconstruct it. I used the NLTK toolkit: https://www.nltk.org/book/ch05.html Then you take all the NNs (nouns) and manually label them as either things or stuff. 

Good luck

**Comment by Delphboy** [comment]
Thank you very much 😄
