### ISSUE TITLE
Old version of COCO-stuff 2017

### ISSUE THREAD

**Issue by davidhalladay** [nightrome/cocostuff#27]
Hello, 

I'm reproducing some results in the recent papers, such as [LDMs](https://arxiv.org/pdf/2112.10752.pdf) and [OC-GAN](https://arxiv.org/pdf/2003.07449.pdf), and I found that most of them conduct experiments on COCO stuff 2017 old version.
In that old version of COCO stuff, the number of training/testing data with detection annotations is about 41k/5k. Is it possible to get this version of COCO-stuff? 

Thank you in advance!

**Comment by nightrome** [comment]
Hi, You can find them at http://images.cocodataset.org/annotations/stuff_annotations_trainval2017.zip.
See also these links for more details:
- https://github.com/nightrome/cocostuff
- https://cocodataset.org/#stuff-2017

**Comment by chrisfan-wc** [comment]
Thanks for help!!

Note: The image id of training and val set can be found in the "annotations/deprecated-challenge2017/train-ids.txt" and "annotations/deprecated-challenge2017/val-ids.txt".
