### ISSUE TITLE
COCO Panoptic Semantic Segmentation versus. COCO Stuff Annotation

### ISSUE THREAD

**Issue by Maddy12** [nightrome/cocostuff#30]
This may be a stupid question, but I am trying to evaluate some models that used the COCO stuff dataset on the COCO Panoptic dataset instead. Is there an example dataloader that would help make COCO Panoptic like COCO STUFF?

**Comment by nightrome** [comment]
Hi. Unfortunately we do not provide such a dataloader. You would have to check how the Panoptic Segmentation authors mapped from the 91 classes in COCO-Stuff to the 53 (?) classes they use.
