### ISSUE TITLE
data link died

### ISSUE THREAD

**Issue by HRLTY** [nightrome/cocostuff#4]
> annotations_trainval2017.zip | Thing-only COCO-style annotations on COCO 2017 trainval | 241 MB

This cannot be downloaded..

```

<Error>
<link type="text/css" id="dark-mode" rel="stylesheet" href=""/>
<style type="text/css" id="dark-mode-custom-style"/>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for project 81,941,577,218 is disabled in state delinquent
</Details>
</Error>
```

**Comment by nightrome** [comment]
Yes, someone is currently looking into it. See also: https://github.com/cocodataset/cocodataset.github.io/issues/12

**Comment by nightrome** [comment]
The download should work again now. Sorry for that.
