### ISSUE TITLE
Can you provide 0-171 label table?

### ISSUE THREAD

**Issue by WJtomcat** [nightrome/cocostuff#6]

**Comment by nightrome** [comment]
A detailed description and examples for each label can be found at:
https://github.com/nightrome/cocostuff/blob/master/labels.md

It's true that we dropped the more machine readable version, I readded it at:
https://github.com/nightrome/cocostuff/blob/master/labels.txt

Note that the labels are 0-182, as the official COCO dataset uses 0-91, but 11 of those classes are empty.
