### ISSUE TITLE
Label values shifted by 1

### ISSUE THREAD

**Issue by Hugstar** [nightrome/cocostuff#7]
Hi!
I'm using the annotations values and it seems like all the annotations are shifted by 1.
For example: 
The person class is labeled with value 0 (but should be 1 according to your mapping list). 
The skis class is labeled with value 34 (but should be 35 according to your mapping list).
The snow class is labeled with value 158 (but should be 159 according to your mapping list).

Note - I'm reading the files in Python. Maybe it has anything to do with the fact that the annotation platform is written in Matlab?

Do you have any idea for the root cause of this mismatch?
Thanks in advance.

Link to the current updated mapping list:
https://github.com/nightrome/cocostuff/blob/master/labels.md

**Comment by nightrome** [comment]
Hi. I suppose you are using the Caffe style annotations? In this case the indices are displaced by -1:

> **Caffe-compatible stuff-thing maps** We suggest using the stuffthingmaps, as they provide all stuff and thing labels in a single .png file per image. Note that the .png files are indexed images, which means they store only the label indices and are typically displayed as grayscale images. To be compatible with most Caffe-based semantic segmentation methods, thing+stuff labels cover indices 0-181 and 255 indicates the 'unlabeled' or void class.
https://github.com/nightrome/cocostuff

If not, please reopen the issue.
